apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-watcher-account
  namespace: simple-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-watcher-clusterbinding
subjects:
  - kind: ServiceAccount
    name: simple-watcher-account
    namespace: simple-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
